// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var services = [
  {
    slug: "custom-pc-building",
    title: "Custom PC Building",
    description: "From part selection to final testing, we build your dream rig from scratch with meticulous attention to detail.",
    startingPrice: 75
  },
  {
    slug: "upgrades",
    title: "Upgrades",
    description: "CPU, GPU, RAM, storage upgrades. We'll help you pick the right parts and install them professionally.",
    startingPrice: 40
  },
  {
    slug: "troubleshooting-repair",
    title: "Troubleshooting & Repair",
    description: "Diagnosing hardware failures, software issues, boot problems, and more. Fast turnaround.",
    startingPrice: 50
  },
  {
    slug: "cleaning-optimization",
    title: "Cleaning & Optimization",
    description: "Deep cleaning, thermal paste replacement, dust removal, OS optimization, and cable management refresh.",
    startingPrice: 35
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List all Monterey Bay PCs services offered (custom builds, upgrades, repair, cleaning) with descriptions and starting prices in USD.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/list-prebuilts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/data/prebuilts.ts
import pcBudget from "npm:@/assets/pc-budget.jpg";
import pcGaming from "npm:@/assets/pc-gaming.jpg";
import pcHighend from "npm:@/assets/pc-highend.jpg";
import pcWorkstation from "npm:@/assets/pc-workstation.jpg";
var prebuilts = [
  {
    slug: "starter",
    image: pcBudget,
    name: "Bay Starter",
    tier: "Starter",
    price: 899,
    tagline: "Solid 1080p gaming on a budget.",
    description: "The perfect entry into PC gaming. Built to crush esports titles at high frame rates and handle modern AAA games at 1080p without breaking the bank.",
    bestFor: ["Esports (Valorant, CS2, Fortnite)", "1080p Gaming", "School & Productivity", "Streaming Light Games"],
    specs: {
      cpu: "AMD Ryzen 5 5600",
      gpu: "NVIDIA RTX 4060 8GB",
      ram: "16GB DDR4 3200MHz",
      storage: "1TB NVMe SSD",
      motherboard: "B550 Gaming Plus",
      psu: "650W 80+ Bronze",
      cooling: "Air Cooler (4 Fans)",
      case: "Mid-Tower with Mesh Front",
      os: "Windows 11 Home"
    },
    performance: {
      resolution: "1080p",
      games: [
        { name: "Fortnite (High)", fps: "180+ FPS" },
        { name: "Valorant", fps: "300+ FPS" },
        { name: "Elden Ring (High)", fps: "60 FPS" },
        { name: "Marvel Rivals (Medium)", fps: "100 FPS" },
        { name: "RDR2 (High)", fps: "75 FPS" }
      ]
    },
    whatsInTheBox: ["Fully assembled & tested PC", "Power cable", "Setup guide", "Lifetime technical support"]
  },
  {
    slug: "mid",
    image: pcGaming,
    name: "Bay Mid",
    tier: "Mid",
    price: 1599,
    tagline: "High refresh 1440p sweet spot.",
    description: "The build most gamers actually want. Smooth 1440p high settings across every modern title with headroom for streaming and creative work.",
    bestFor: ["1440p Gaming High/Ultra", "Streaming & Content Creation", "VR Ready", "Multitasking"],
    specs: {
      cpu: "AMD Ryzen 7 7700X",
      gpu: "NVIDIA RTX 4070 Super 12GB",
      ram: "32GB DDR5 6000MHz",
      storage: "2TB NVMe Gen4 SSD",
      motherboard: "B650 Tomahawk",
      psu: "750W 80+ Gold",
      cooling: "240mm AIO Liquid Cooler",
      case: "Tempered Glass ATX",
      os: "Windows 11 Home"
    },
    performance: {
      resolution: "1440p",
      games: [
        { name: "Fortnite (Ultra)", fps: "165 FPS" },
        { name: "Valorant", fps: "400+ FPS" },
        { name: "Elden Ring (Max)", fps: "60 FPS" },
        { name: "Marvel Rivals (High)", fps: "140 FPS" },
        { name: "RDR2 (Ultra)", fps: "95 FPS" }
      ]
    },
    whatsInTheBox: ["Fully assembled & tested PC", "Power cable", "Setup guide", "Lifetime technical support"]
  },
  {
    slug: "high-end",
    image: pcHighend,
    name: "Bay High-End",
    tier: "High-End",
    price: 2799,
    tagline: "4K ready, no compromises.",
    description: "A serious enthusiast machine. Smooth 4K gaming, fast video editing, and silent operation under load. Built to last and easy to upgrade.",
    bestFor: ["4K Gaming", "Video Editing & 3D Work", "Streaming + Gaming Simultaneously", "Future-Proof"],
    specs: {
      cpu: "Intel Core i7-14700K",
      gpu: "NVIDIA RTX 4080 Super 16GB",
      ram: "32GB DDR5 6400MHz",
      storage: "2TB NVMe Gen4 + 4TB HDD",
      motherboard: "Z790 Pro",
      psu: "850W 80+ Gold Modular",
      cooling: "360mm AIO Liquid Cooler",
      case: "Premium Airflow Case (ARGB)",
      os: "Windows 11 Pro"
    },
    performance: {
      resolution: "4K",
      games: [
        { name: "Fortnite (Epic)", fps: "120 FPS" },
        { name: "Valorant", fps: "300+ FPS" },
        { name: "Elden Ring (Max)", fps: "60 FPS" },
        { name: "Marvel Rivals (Ultra)", fps: "110 FPS" },
        { name: "RDR2 (Ultra)", fps: "75 FPS" }
      ]
    },
    whatsInTheBox: ["Fully assembled & tested PC", "Power cables", "Setup guide", "Lifetime technical support", "Premium box packaging"]
  },
  {
    slug: "extreme",
    image: pcWorkstation,
    name: "Bay Extreme",
    tier: "Extreme",
    price: 4499,
    tagline: "The flagship. Everything maxed.",
    description: "Our no-compromise flagship. The fastest consumer hardware available, hand-tuned and stress tested. For the player who wants the best of the best.",
    bestFor: ["4K Ultra @ High FPS", "Pro Content Creation", "AI & 3D Rendering", "Showpiece Build"],
    specs: {
      cpu: "AMD Ryzen 9 9950X",
      gpu: "NVIDIA RTX 5090 32GB",
      ram: "64GB DDR5 6400MHz CL30",
      storage: "4TB NVMe Gen5 + 8TB HDD",
      motherboard: "X870E Hero",
      psu: "1200W 80+ Platinum Modular",
      cooling: "Custom 360mm AIO + 9 ARGB Fans",
      case: "Showcase Tempered Glass Tower",
      os: "Windows 11 Pro"
    },
    performance: {
      resolution: "4K Ultra",
      games: [
        { name: "Fortnite (Epic + RT)", fps: "180+ FPS" },
        { name: "Valorant", fps: "500+ FPS" },
        { name: "Elden Ring (Max)", fps: "60 FPS" },
        { name: "Marvel Rivals (Ultra)", fps: "180 FPS" },
        { name: "RDR2 (Ultra)", fps: "140 FPS" },
        { name: "Cyberpunk 2077 (RT Ultra)", fps: "90 FPS" }
      ]
    },
    whatsInTheBox: [
      "Fully assembled & tested PC",
      "Premium braided cables",
      "Setup & overclock guide",
      "Lifetime priority technical support",
      "Signed build certificate"
    ]
  }
];
var getPrebuilt = (slug) => prebuilts.find((p) => p.slug === slug);

// src/lib/mcp/tools/list-prebuilts.ts
var list_prebuilts_default = defineTool2({
  name: "list_prebuilts",
  title: "List prebuilt PCs",
  description: "List all prebuilt PC models offered by Monterey Bay PCs with tier, price (USD), tagline, and slug. Use `get_prebuilt` for full specs and performance benchmarks.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = prebuilts.map((p) => ({
      slug: p.slug,
      name: p.name,
      tier: p.tier,
      price: p.price,
      tagline: p.tagline
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { prebuilts: summary }
    };
  }
});

// src/lib/mcp/tools/get-prebuilt.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var get_prebuilt_default = defineTool3({
  name: "get_prebuilt",
  title: "Get prebuilt PC details",
  description: "Get full details for one prebuilt PC by slug \u2014 specs, performance benchmarks, what's in the box, and best use cases.",
  inputSchema: {
    slug: z.string().min(1).describe(
      `Prebuilt slug. One of: ${prebuilts.map((p) => p.slug).join(", ")}.`
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const pc = getPrebuilt(slug);
    if (!pc) {
      return {
        content: [{ type: "text", text: `No prebuilt found with slug "${slug}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(pc, null, 2) }],
      structuredContent: { prebuilt: pc }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var contact = {
  business: "Monterey Bay PCs",
  location: "Monterey Bay, California",
  email: "montereybaypc@gmail.com",
  instagram: "https://instagram.com/montereybaypcs",
  website: "https://montereybaypcs.com",
  serviceArea: "Local pickup in Monterey Bay; local delivery within 30 miles ($75)."
};
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Get contact information for Monterey Bay PCs \u2014 email, Instagram, website, and service area.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "monterey-bay-pcs-mcp",
  title: "Monterey Bay PCs",
  version: "0.1.0",
  instructions: "Public catalog for Monterey Bay PCs, a local custom PC builder and repair shop in the Monterey Bay area. Use `list_services` for repair/build services, `list_prebuilts` + `get_prebuilt` for prebuilt PC models and specs, and `get_contact_info` for how to reach the shop.",
  tools: [list_services_default, list_prebuilts_default, get_prebuilt_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
